apiVersion: batch/v1
kind: Job
metadata:
  name: build-image
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: build-vault-k8s-arm64
    spec:
      restartPolicy: Never

      containers:
      - name: build
        image: nazarewk/rpi-container-image-builder:v0.0.1
        imagePullPolicy: Always

        securityContext:
          privileged: true

        env:
        - name: IMAGE_REPOSITORY
          value: nazarewk/vault-k8s-arm64
        - name: APP_VERSION
          value: '0.3.0'
        - name: IMAGE
          value: "$(IMAGE_REPOSITORY):v$(APP_VERSION)"

        command:
        - /bin/bash
        - -xeEuo
        - pipefail
        - -c
        - |-
          # see for --squash : https://github.com/containers/image/issues/733
          buildah bud --squash -t "${IMAGE}" .
          buildah push --authfile /repository-auth-secrets/auth.json "${IMAGE}"

        workingDir: /build
        volumeMounts:
        - name: sources
          mountPath: /build
        - name: repository-auth-secrets
          mountPath: /repository-auth-secrets

      volumes:
      - name: sources
        configMap:
          name: sources
      - name: repository-auth-secrets
        secret:
          secretName: repository-auth-secrets
